name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
     -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
     -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
     -
        name: Build and push (latest)
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/rust-project-management:latest
     - uses: actions/checkout@v4
     - name: Build the Docker image
       run: docker build . --file docker/debian/Dockerfile --tag my-image-name:$(date +%s1)
     # -
     #    name: Build and push (debian)
     #    run: docker build -t ${{ vars.DOCKERHUB_USERNAME }}/rust-project-management:debian -f ./docker/debian/Dockerfile .
     # -
     #    name: Build and push (debian)
     #    uses: docker/build-push-action@v6
     #    with:
     #      context: .
     #      file: ./docker/debian/Dockerfile
     #      push: true
     #      tags: ${{ vars.DOCKERHUB_USERNAME }}/rust-project-management:debian
