name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64
    steps:
      - uses: actions/checkout@v4
      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildx-version: latest
          configure:
            use: docker-credential-github
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (latest)
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rust-project-management:latest
          platforms: ${{ matrix.os }}_${matrix.arch}
      - name: Build and push (debian)
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rust-project-management:debian
          platforms: ${{ matrix.os }}_${matrix.arch}
          dockerfile: docker/debian/Dockerfile
